export interface Question {
  id: string;
  text: string;
  trait: string;
  facet: string;
  reverse: boolean;
}

// 🏆 CANONICAL SCORING CONTRACT
// This is the ONLY valid format for scoring results.
// Both Backend and Fallback Engine MUST return this exact structure.
export interface CanonicalScoringResponse {
  ocean: {
    O: number;
    C: number;
    E: number;
    A: number;
    N: number;
  };
  assessment_id: string; // Critical for tracking
  persona_id: string; // e.g., "architect" or "intp"
  mbti_proxy: string; // e.g., "INTP"
  confidence: number; // 0-1 (Global confidence score)
  metadata: {
    quiz_type: "smart30" | "full180" | "quick" | "standard" | "full";
    engine_version: string;
    scoring_version: string;
    timestamp: number;
    is_fallback?: boolean;
    platform?: "web" | "mobile";
  };
  // Optional detailed data (can be used for UI but not core identity)
  facets?: Record<string, number | null>;
  traits_detailed?: Record<string, number | null>;
}

// @deprecated - Use CanonicalScoringResponse
export interface BackendAssessmentResponse {
  assessment_id: string;
  traits: Record<string, number | null>;
  facets: Record<string, number | null>;
  confidence: Record<string, any>;
  dominant: {
    mbti_proxy: string | null;
    neuroticism_level?: string | null;
    personality_code?: string | null;
  };
  top_facets: any[];
  coverage: number;
  responses_count: number;
  has_complete_profile?: boolean;
  is_complete?: boolean;
  traits_with_data?: string[];
  needs_retake?: boolean;
  needs_retake_reason?: string;
  // New contract field wrapper for gradual migration
  contract_v2?: CanonicalScoringResponse;
  explanation?: any;
  answers?: Record<string, number>;
}

// Web-friendly format (Solution D: supports null for insufficient data)
export interface AssessmentResult {
  traits: Record<string, number | null>;  // Can be null if insufficient data
  facets: Record<string, number | null>;  // Can be null if insufficient data
  mbti: string | null;  // Can be null if incomplete profile
  assessment_id: string;
  has_complete_profile?: boolean;  // True if all 5 traits have data
  is_complete?: boolean; // Added to match backend
  traits_with_data?: string[];  // List of trait codes with sufficient data
  needs_retake?: boolean;  // Solution C: True if assessment is invalid
  needs_retake_reason?: string;  // Solution C: Reason why retake is needed
  is_offline?: boolean; // True if result was generated by local fallback engine
  explanation?: any; // AI explanation
  answers?: Record<string, number>;
}

// Request format for submitting answers
export interface AssessmentResponse {
  question_id: string;
  response: number;
}

// Backend explanation response format
export interface ExplanationResponse {
  assessment_id?: string;
  explanation?: string;
  summary?: string;
  steps?: string[];
  confidence_note?: string;
  model_name?: string;
  tokens_used?: number;
  generation_time_ms?: number;
}

// Parsed explanation format for UI (new persona-based format)
export interface ParsedExplanation {
  // New persona format
  persona_title?: string;
  vibe_summary?: string;
  strengths: string[];
  growth_edges?: string[];
  how_you_show_up?: string;
  tagline?: string;
  model_name?: string;
  // Backward compatibility fields
  summary: string;
  cautions: string[];
  tone: string;
}

export interface AssessmentHistoryItem {
  assessment_id: string;
  created_at: string;
  traits: Record<string, number>;
  facets: Record<string, number>;
  mbti: string;
  summary?: string;
}

export interface ShareResponse {
  url: string;
  share_id: string;
}

export interface SharedAssessmentResponse {
  assessment_id: string;
  traits: Record<string, number>;
  facets: Record<string, number>;
  mbti: string;
  created_at: string;
  explanation?: string;
}
